version: "3.8"
services:
  db: 
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: badminton
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data: